name: Generate ASCII Art

on: push

jobs:
  gen-ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Repo files 
        run: ls -ltra

      - name: Shell Execution
        run: ./ascii-script.sh 
