name: GKJ Workflow

on: push 

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Hello! 
          run: echo "GKJ-001 Workflow"
        - name: checkout
          uses: actions/checkout@v5
        
        - name: List Files 
          run: ls 

        - name: Read file 
          run: cat README.md

