name: Multiple Jobs 

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest 
        steps: 
         - name: install Cowsay Program
           run: sudo apt-get install cowsay -y 

         - name: Execute Cowsay CMD
           run: cowsay -f dragon "Run for Cover, I am DRAGON.." >> dragon.txt

        
         - name: Upload a Build Artifact
           uses: actions/upload-artifact@v5.0.0
           with:
            name: dragon-file
            path: dragon.txt

    Test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v5.0.0
          with:
            name: dragon-file

    Deploy_job_3:
        needs: [Test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy 
          run: echo Deploying

    

